# Generated by Django 4.1.2 on 2022-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadtrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=200)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
