# Generated by Django 4.1.2 on 2022-10-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('contacted', models.BooleanField(default=False, verbose_name='contacted ?')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.contact')),
                ('roadtrip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.roadtrip')),
            ],
        ),
    ]
